/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness probe with per-dependency sub-checks.
         *
         *     Returns HTTP 200 unconditionally — Fly uses the status code as a
         *     process-up signal, and a degraded data layer should not flap the
         *     container restart loop. Callers inspect the body to distinguish
         *     healthy from degraded states:
         *
         *     * ``status``: ``"ok"`` only when every sub-check is ``"ok"``;
         *       ``"degraded"`` otherwise.
         *     * ``db`` / ``redis``: ``"ok"`` or ``"down"`` per the corresponding
         *       ``ping_*`` helper.
         *     * ``version``: package version, useful for confirming a deploy.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
