// @auxd/shared-types — auto-generated bindings to the FastAPI OpenAPI schema.
//
// The `paths`, `components`, and `operations` exports come from `api.ts`,
// which is regenerated by `pnpm --filter @auxd/shared-types codegen`
// (T028 pipeline). Backend changes that alter the schema must be paired
// with a regenerated `api.ts` — CI's `codegen:check` enforces this.

export * from "./api";

// Smoke-test export retained from T003 — proves workspace resolution
// works end-to-end without depending on the codegen having run yet.
export function greeting(): string {
  return "Hello from @auxd/shared-types.";
}
